/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.udf.edu;

import operations.Operations;
import javax.swing.Timer;
/**
 *
 * @author slabj
 */
public class Calc extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calc.class.getName());

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        SumButton = new javax.swing.JButton();
        MinusButton = new javax.swing.JButton();
        DivideNumber = new javax.swing.JButton();
        Xbutton = new javax.swing.JButton();
        TextFieldCalc = new javax.swing.JTextField();
        buttonNumber1 = new javax.swing.JButton();
        ButtonNumber2 = new javax.swing.JButton();
        ButtonNumber3 = new javax.swing.JButton();
        ButtonNumber4 = new javax.swing.JButton();
        ButtonNumber5 = new javax.swing.JButton();
        ButtonNumber6 = new javax.swing.JButton();
        ButtonNumber7 = new javax.swing.JButton();
        ButtonNumber8 = new javax.swing.JButton();
        ButtonNumber9 = new javax.swing.JButton();
        ButtonNumber0 = new javax.swing.JButton();
        EqualButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculator"));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SumButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SumButton.setText("+");
        SumButton.addActionListener(this::SumButtonActionPerformed);

        MinusButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MinusButton.setText("-");
        MinusButton.addActionListener(this::MinusButtonActionPerformed);

        DivideNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DivideNumber.setText("/");
        DivideNumber.addActionListener(this::DivideNumberActionPerformed);

        Xbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Xbutton.setText("X");
        Xbutton.addActionListener(this::XbuttonActionPerformed);

        TextFieldCalc.addActionListener(this::TextFieldCalcActionPerformed);

        buttonNumber1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonNumber1.setText("1");
        buttonNumber1.addActionListener(this::buttonNumber1ActionPerformed);

        ButtonNumber2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonNumber2.setText("2");
        ButtonNumber2.addActionListener(this::ButtonNumber2ActionPerformed);

        ButtonNumber3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonNumber3.setText("3");
        ButtonNumber3.addActionListener(this::ButtonNumber3ActionPerformed);

        ButtonNumber4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonNumber4.setText("4");
        ButtonNumber4.addActionListener(this::ButtonNumber4ActionPerformed);

        ButtonNumber5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonNumber5.setText("5");
        ButtonNumber5.addActionListener(this::ButtonNumber5ActionPerformed);

        ButtonNumber6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonNumber6.setText("6");
        ButtonNumber6.addActionListener(this::ButtonNumber6ActionPerformed);

        ButtonNumber7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonNumber7.setText("7");
        ButtonNumber7.addActionListener(this::ButtonNumber7ActionPerformed);

        ButtonNumber8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonNumber8.setText("8");
        ButtonNumber8.addActionListener(this::ButtonNumber8ActionPerformed);

        ButtonNumber9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonNumber9.setText("9");
        ButtonNumber9.addActionListener(this::ButtonNumber9ActionPerformed);

        ButtonNumber0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonNumber0.setText("0");
        ButtonNumber0.addActionListener(this::ButtonNumber0ActionPerformed);

        EqualButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EqualButton.setText("=");
        EqualButton.addActionListener(this::EqualButtonActionPerformed);

        ClearButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ClearButton.setText("C");
        ClearButton.addActionListener(this::ClearButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldCalc)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonNumber4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonNumber7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EqualButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonNumber2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonNumber5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonNumber8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonNumber0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonNumber3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonNumber6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonNumber9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClearButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DivideNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TextFieldCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DivideNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber0, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String operator = "";
    double number1 = 0;
    double number2 = 0;
    Operations operation = new Operations();
    int countTimer=0;
    
   
    private void SumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumButtonActionPerformed
        // TODO add your handling code here:
        try{
            number1 = Double.parseDouble(TextFieldCalc.getText());
            operation.firstNumber = number1;
            TextFieldCalc.setText("");
            operator = "+";   
        }catch(Exception error){
            TextFieldCalc.setText("Error");
            Timer time = new Timer(1000,e->{
                countTimer++;
                TextFieldCalc.setText(""); 
                Timer sumTimer =(Timer)e.getSource();
                sumTimer.stop();
            });
            time.start();
            
        }          
    }//GEN-LAST:event_SumButtonActionPerformed

    private void MinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusButtonActionPerformed
        // TODO add your handling code here:
        try{
            number1 = Double.parseDouble(TextFieldCalc.getText());
            operation.firstNumber = number1;
            TextFieldCalc.setText("");
            operator = "-";
        } catch (Exception error) {
            TextFieldCalc.setText("Error");
            Timer timer = new Timer(1000, e -> {
                TextFieldCalc.setText("");
                Timer minusTimer=(Timer)e.getSource();
                minusTimer.stop();
            });
            timer.start();
        }
        
    }//GEN-LAST:event_MinusButtonActionPerformed

    private void DivideNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideNumberActionPerformed
        // TODO add your handling code here:
        try{
            number1 = Double.parseDouble(TextFieldCalc.getText());
            operation.firstNumber = number1;
            TextFieldCalc.setText("");
            operator="/";
        }catch(Exception error){
            TextFieldCalc.setText("Error");
            Timer timer = new Timer(1000, e -> {
                TextFieldCalc.setText("");
                Timer divideTimer = (Timer)e.getSource();
                divideTimer.stop();
            });
            timer.start();
        }
        
    }//GEN-LAST:event_DivideNumberActionPerformed

    private void XbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XbuttonActionPerformed
        // TODO add your handling code here:
        try{        
            number1 = Double.parseDouble(TextFieldCalc.getText());
            operation.firstNumber = number1;
            TextFieldCalc.setText("");
            operator="*";
        }catch(Exception error){
            TextFieldCalc.setText("Error!");
            Timer timer = new Timer(1000, e -> {
                TextFieldCalc.setText("");
                Timer timesTimer = (Timer) e.getSource();
                timesTimer.stop();
            });
            
            timer.start();
            
        }
    }//GEN-LAST:event_XbuttonActionPerformed

    private void buttonNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber1ActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText(TextFieldCalc.getText()+"1");
    }//GEN-LAST:event_buttonNumber1ActionPerformed

    private void ButtonNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber2ActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText(TextFieldCalc.getText()+"2");
    }//GEN-LAST:event_ButtonNumber2ActionPerformed

    private void ButtonNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber3ActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText(TextFieldCalc.getText()+"3");
    }//GEN-LAST:event_ButtonNumber3ActionPerformed

    private void ButtonNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber4ActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText(TextFieldCalc.getText()+"4");
    }//GEN-LAST:event_ButtonNumber4ActionPerformed

    private void ButtonNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber5ActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText(TextFieldCalc.getText()+"5");
    }//GEN-LAST:event_ButtonNumber5ActionPerformed

    private void ButtonNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber6ActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText(TextFieldCalc.getText()+"6");
    }//GEN-LAST:event_ButtonNumber6ActionPerformed

    private void ButtonNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber7ActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText(TextFieldCalc.getText()+"7");
    }//GEN-LAST:event_ButtonNumber7ActionPerformed

    private void ButtonNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber8ActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText(TextFieldCalc.getText()+"8");
    }//GEN-LAST:event_ButtonNumber8ActionPerformed

    private void ButtonNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber9ActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText(TextFieldCalc.getText()+"9");
    }//GEN-LAST:event_ButtonNumber9ActionPerformed

    private void ButtonNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber0ActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText(TextFieldCalc.getText()+"0");
    }//GEN-LAST:event_ButtonNumber0ActionPerformed

    private void TextFieldCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCalcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCalcActionPerformed

    private void EqualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            number2 = Double.parseDouble(TextFieldCalc.getText());
            if (operator == "+") {
                operation.secondNumber = number2;
                TextFieldCalc.setText(String.valueOf(operation.sumNumbers()));
            } else if (operator == "-") {
                operation.secondNumber = number2;
                TextFieldCalc.setText(String.valueOf(operation.minusNumbers()));
            } else if (operator == "*") {
                operation.secondNumber = number2;
                TextFieldCalc.setText(String.valueOf(operation.timesNumbers()));
            } else if (operator  == "/") {
                operation.secondNumber = number2;
                TextFieldCalc.setText(String.valueOf(operation.divisionNumbers()));
            }
        }catch(Exception error){
            TextFieldCalc.setText("Error!");
            Timer time = new Timer(1000,e->{
                TextFieldCalc.setText("");
                Timer equalTimerErr = (Timer)e.getSource();
                equalTimerErr.stop();
            });
            time.start();
        }

    }//GEN-LAST:event_EqualButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        TextFieldCalc.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonNumber0;
    private javax.swing.JButton ButtonNumber2;
    private javax.swing.JButton ButtonNumber3;
    private javax.swing.JButton ButtonNumber4;
    private javax.swing.JButton ButtonNumber5;
    private javax.swing.JButton ButtonNumber6;
    private javax.swing.JButton ButtonNumber7;
    private javax.swing.JButton ButtonNumber8;
    private javax.swing.JButton ButtonNumber9;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DivideNumber;
    private javax.swing.JButton EqualButton;
    private javax.swing.JButton MinusButton;
    private javax.swing.JButton SumButton;
    private javax.swing.JTextField TextFieldCalc;
    private javax.swing.JButton Xbutton;
    private javax.swing.JButton buttonNumber1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
